plugin:
  build: .
  volumes:
    - .:/home/app/current
  command:  npm run intTest #top -b
  external_links:
    - mfworkflows_postgres_1:postgres
    - mfworkflows_eventstore_1:eventstore
  environment:
    DEBUG: true
    NODE_ENV: development
    APPLICATION_NAME: Projections
