version: "2"
services:
  projections:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app
    command: npm start #top -b #
    env_file:
      - ./.env
